name: Avro Compatibility Tests
on: [push, pull_request]
jobs:
  test:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}/kotlin ${{ matrix.kotlin }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.0", "1.10.1", "1.10.2"]
        gradle: ["5.1", "6.8.3"]
        java: ["8"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --info testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
