name: CI Build
on: [push, pull_request]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: --no-daemon --info --stacktrace build
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
    - uses: codecov/codecov-action@v1
      with:
        file: ./build/reports/jacoco/test/jacocoTestReport.xml
        fail_ci_if_error: true
#  compatibility-tests:
#    name: "Compatibility: avro ${{ matrix.avro }}/gradle ${{ matrix.gradle }}/java ${{ matrix.java }}/os ${{ matrix.os }}"
#    needs: [build]
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        avro: ["1.10.0", "1.10.1", "1.10.2"]
#        gradle: [
#            "1.3.20", "1.3.21", "1.3.30", "1.3.31", "1.3.40", "1.3.41", "1.3.50", "1.3.60", "1.3.61", "1.3.70", "1.3.71", "1.3.72",
#            "1.4.0", "1.4.10", "1.4.20", "1.4.21",
#            "5.1", "5.1.1", "5.2", "5.2.1", "5.3", "5.3.1", "5.4", "5.4.1", "5.5", "5.5.1", "5.6", "5.6.1", "5.6.2", "5.6.3", "5.6.4",
#            "6.0", "6.0.1", "6.1", "6.1.1", "6.2", "6.2.1", "6.2.2",
#            "6.3", "6.4", "6.4.1", "6.5", "6.5.1", "6.6", "6.6.1",
#            "6.7", "6.7.1", "6.8", "6.8.1", "6.8.2", "6.8.3"
#        ]
#        java: ["8", "11", "13", "14", "15"] # All supported major versions
##        java: [ "8", "11" ] # LTS versions only; 17 will be the next one
#        kotlin: [
#            "1.2.20", "1.2.21",
#            "1.2.30", "1.2.31", "1.2.40", "1.2.41", "1.2.50", "1.2.51", "1.2.60", "1.2.61", "1.2.70", "1.2.71",
#            "1.3.0", "1.3.10", "1.3.11",
#            "1.3.20", "1.3.21", "1.3.30", "1.3.31", "1.3.40", "1.3.41", "1.3.50", "1.3.60", "1.3.61", "1.3.70", "1.3.71", "1.3.72",
#            "1.4.0", "1.4.10", "1.4.20", "1.4.21"
#        ]
#        # Exclude mac as it's unreliable at the moment
#        # See https://github.com/actions/virtual-environments/issues/736
#        os: ["ubuntu-latest", "windows-latest"]
##        os: [ "ubuntu-latest" ] # Only a single OS to cut down on execution time
#      fail-fast: true
#    steps:
#    - name: Check out repository
#      uses: actions/checkout@v2
#    - name: Set up Java ${{ matrix.java }}
#      uses: actions/setup-java@v1
#      with:
#        java-version: ${{ matrix.java }}
#        architecture: x64
#    - name: Output Avro version
#      run: echo "Avro ${{ matrix.avro }}"
#    - name: Output Java version
#      run: java -version
#    - name: Output Gradle version
#      uses: eskatos/gradle-command-action@v1
#      with:
#        arguments: --version
#    - name: Run recent version compatibility tests
#      uses: eskatos/gradle-command-action@v1
#      with:
#        arguments: --info testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }} -PkotlinVersion=${{ matrix.kotlin }}
#        dependencies-cache-enabled: true
#    - name: Stop Gradle Daemon
#      uses: eskatos/gradle-command-action@v1
#      with:
#        arguments: --stop
