name: Kotlin Plugin Compatibility Tests
on: [push, pull_request]
jobs:
  check-compat:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}/kotlin ${{ matrix.kotlin }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.2"]
        gradle: ["5.1", "6.8.3"]
        java: ["8", "11"]
        kotlin: [
            "1.2.20", "1.2.21",
            "1.2.30", "1.2.31", "1.2.40", "1.2.41", "1.2.50", "1.2.51", "1.2.60", "1.2.61", "1.2.70", "1.2.71",
            "1.3.0", "1.3.10", "1.3.11",
            "1.3.20", "1.3.21", "1.3.30", "1.3.31", "1.3.40", "1.3.41", "1.3.50", "1.3.60", "1.3.61", "1.3.70", "1.3.71", "1.3.72",
            "1.4.0", "1.4.10", "1.4.20", "1.4.21"
        ]
    steps:
      - uses: ./.github/actions/run-tests
        with:
          task-name: testKotlinPluginCompatibility
          avro-version: ${{ matrix.avro }}
          gradle-version: ${{ matrix.gradle }}
          java-version: ${{ matrix.java }}
          kotlin-plugin-version: ${{ matrix.kotlin }}
#  java-11:
#    name: "Compatibility: java ${{ matrix.java }}/kotlin ${{ matrix.kotlin }}"
#    runs-on: "ubuntu-latest"
#  compatibility-tests:
#    name: "Compatibility: avro ${{ matrix.avro }}/gradle ${{ matrix.gradle }}/java ${{ matrix.java }}/os ${{ matrix.os }}"
#    needs: [build]
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        avro: ["1.10.0", "1.10.1", "1.10.2"]
#        gradle: [
#            "1.3.20", "1.3.21", "1.3.30", "1.3.31", "1.3.40", "1.3.41", "1.3.50", "1.3.60", "1.3.61", "1.3.70", "1.3.71", "1.3.72",
#            "1.4.0", "1.4.10", "1.4.20", "1.4.21",
#            "5.1", "5.1.1", "5.2", "5.2.1", "5.3", "5.3.1", "5.4", "5.4.1", "5.5", "5.5.1", "5.6", "5.6.1", "5.6.2", "5.6.3", "5.6.4",
#            "6.0", "6.0.1", "6.1", "6.1.1", "6.2", "6.2.1", "6.2.2",
#            "6.3", "6.4", "6.4.1", "6.5", "6.5.1", "6.6", "6.6.1",
#            "6.7", "6.7.1", "6.8", "6.8.1", "6.8.2", "6.8.3"
#        ]
#        java: ["8", "11", "13", "14", "15"] # All supported major versions
##        java: [ "8", "11" ] # LTS versions only; 17 will be the next one
#        kotlin: [
#            "1.2.20", "1.2.21",
#            "1.2.30", "1.2.31", "1.2.40", "1.2.41", "1.2.50", "1.2.51", "1.2.60", "1.2.61", "1.2.70", "1.2.71",
#            "1.3.0", "1.3.10", "1.3.11",
#            "1.3.20", "1.3.21", "1.3.30", "1.3.31", "1.3.40", "1.3.41", "1.3.50", "1.3.60", "1.3.61", "1.3.70", "1.3.71", "1.3.72",
#            "1.4.0", "1.4.10", "1.4.20", "1.4.21"
#        ]
#        # Exclude mac as it's unreliable at the moment
#        # See https://github.com/actions/virtual-environments/issues/736
#        os: ["ubuntu-latest", "windows-latest"]
##        os: [ "ubuntu-latest" ] # Only a single OS to cut down on execution time
#      fail-fast: true
#    steps:
#    - name: Check out repository
#      uses: actions/checkout@v1
#    - name: Set up Java ${{ matrix.java }}
#      uses: actions/setup-java@v1
#      with:
#        java-version: ${{ matrix.java }}
#        architecture: x64
#    - name: Output Avro version
#      run: echo "Avro ${{ matrix.avro }}"
#    - name: Output Java version
#      run: java -version
#    - name: Output Gradle version
#      uses: eskatos/gradle-command-action@v1
#      with:
#        arguments: --version
#    - name: Run recent version compatibility tests
#      uses: eskatos/gradle-command-action@v1
#      with:
#        arguments: --info testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }} -PkotlinVersion=${{ matrix.kotlin }}
#        dependencies-cache-enabled: true
#    - name: Stop Gradle Daemon
#      uses: eskatos/gradle-command-action@v1
#      with:
#        arguments: --stop
#
#
#//def gradle5KotlinVersions = []
# //if (!JavaVersion.current().java10Compatible) {
# //    // Java 10 support was added in Kotlin 1.2.30
# //    gradle5KotlinVersions.addAll([
# //        "1.2.20", "1.2.21",
# //    ])
# //}
# //gradle5KotlinVersions.addAll([
# //    "1.2.30", "1.2.31", "1.2.40", "1.2.41", "1.2.50", "1.2.51", "1.2.60", "1.2.61", "1.2.70", "1.2.71",
# //    "1.3.0", "1.3.10", "1.3.11",
# //])
# //def latestGradleKotlinVersions = [
# //    "1.3.20", "1.3.21", "1.3.30", "1.3.31", "1.3.40", "1.3.41", "1.3.50", "1.3.60", "1.3.61", "1.3.70", "1.3.71", "1.3.72",
# //    "1.4.0", "1.4.10", "1.4.20", "1.4.21"
# //]
# //def kotlinVersions = gradle5KotlinVersions + latestGradleKotlinVersions
# //def keyKotlinVersions = [] // First and last version for each supported line
# //// Determine first supported version
# //if (!JavaVersion.current().java10Compatible) {
# //    // Java 10 support was added in Kotlin 1.2.30
# //    keyKotlinVersions.add("1.2.20")
# //} else {
# //    keyKotlinVersions.add("1.2.30")
# //}
# //keyKotlinVersions.addAll([
# //    "1.2.71",
# //    "1.3.0", "1.3.72", // First and last version for 1.3.x line
# //    "1.4.0", "1.4.21", // First and last version for 1.4.x line
# //])
# //def pre5_3KotlinVersion = "1.3.72" // Kotlin plugin 1.4.x appears to require Gradle 5.3+
